name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build
        run: |
          unzip -q *.zip -d source_code
          cd source_code
          if [ -d * ]; then cd */; fi
          chmod +x gradlew
          ./gradlew assembleDebug
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: '**/build/outputs/apk/debug/*.apk'
		  
